### ISSUE TITLE
Separate README and CHANGELOG into separate files

### ISSUE THREAD

**Issue by bundgaard** [stakater/application#161]
Hello

It would be easier for 3rd party people, if you would separate the README and the CHANGELOG into their own files.

Thanks

**Comment by rasheedamir** [comment]
agreed @bundgaard PRs are welcome

**Comment by bundgaard** [comment]
Yes, but that will happen to be done with the point of automations and as I do not have access to automate in your repository I cannot do it. So in the end it would be up to you and your employees to make this happen.
Also it would be beneficial if you want to extend your software to more companies.
I do not work where your software is deployed anymore, so you can close as you see fit.

**Comment by rasheedamir** [comment]
https://github.com/stakater/application/pull/207
