### ISSUE TITLE
Automate helm documentation update

### ISSUE THREAD

**Issue by aslafy-z** [stakater/application#242]
There are some tools out there to automatically generate helm chart documentation from the values and comments. It would ensure we don't miss any entries and enforce comments in the value file.

**Comment by rasheedamir** [comment]
@aslafy-z can you plz work on this and automate it?

**Comment by aslafy-z** [comment]
I will try to get some time to work on this and let you know.

**Comment by karl-johan-grahn** [comment]
https://github.com/stakater/application/pull/335
