### ISSUE TITLE
add lifeCycle block to the deployment container

### ISSUE THREAD

**Issue by dmitry-mightydevops** [stakater/application#299]
**Is your feature request related to a problem? Please describe.**
Add ability to define the lifeCycle block for the deployment container
https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/

### The purpose:
![image](https://github.com/stakater/application/assets/70822710/9ee9f18c-88cf-4ebc-a4f8-7ae833478c19)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MuneebAijaz** [comment]
@dmitry-mightydevops we appreciate PRs for contribution, feel free to open one.

**Comment by rtest12** [comment]
@MuneebAijaz 
Could you please take a look at the related pr, it's open.
