### ISSUE TITLE
Change Log NEEDED

### ISSUE THREAD

**Issue by mhkarimi1383** [stakater/application#318]
**Is your feature request related to a problem? Please describe.**
There is no change log for major updates to have a upgrade path to upgrade this chart

**Describe the solution you'd like**
a simple `CHANGELOG` file

**Describe alternatives you've considered**
Reading changes commit by commit 

**Additional context**

**Comment by aslafy-z** [comment]
Duplicate https://github.com/stakater/application/issues/241
