### ISSUE TITLE
Allow CI workflow edit for maintainers

### ISSUE THREAD

**Issue by aslafy-z** [stakater/application#338]
See https://github.com/orgs/community/discussions/26829#discussioncomment-3253580

**Comment by rasheedamir** [comment]
@aslafy-z I changed your permissions to Admin level

**Comment by aslafy-z** [comment]
@rasheedamir this change can ease some things but does not solve the issue.

**Comment by karl-johan-grahn** [comment]
@aslafy-z can you explain what you want to achieve? Can you give some examples of what you want to do, we need more context to understand what action we need to take.
